### ISSUE TITLE
Recent changes cause issues with request urls in sockjs-client

### ISSUE THREAD

**Issue by octatone** [unshiftio/url-parse#23] opened 2016-03-29 15:31 UTC
Hello [I filed this issue with sockjs-client](https://github.com/sockjs/sockjs-client/issues/301), but I wanted to inform you as well.

It seems the release yesterday for `url-parse` has bugs around host and port combinations.

I am seeing urls with duplicate host:port combinations in the string:
`http://localhost:3000/localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=1459265140328-0`

Reverting to 1.0.1 for `url-parse` resolves the duplicate host:port

**Comment by 3rd-Eden** [comment] 2016-03-29 15:37
Well, fuck.

**Comment by sirjasiu** [comment] 2016-03-30 07:32
Unfortunately in current solution you assume that global.location.slashes are always available, while window.location.slashes is undefined. ;)

**Comment by hayeah** [comment] 2016-03-30 08:08
I believe the bug is with the protocol slashes handling in `Url.prototype.toString`:

```
  var result = protocol + (url.slashes ? '//' : '');
```

https://github.com/unshiftio/url-parse/blob/f30e236d4f39b1f8ee47f6fc29564944e65a721a/index.js#L242

The conditional is backward

**Comment by lpinca** [comment] 2016-03-30 17:37
I close this, please post back if the issue is not fixed.

**Closed by lpinca** 2016-03-30 17:37 UTC
