### ISSUE TITLE
Email with a plus is not decoded

### ISSUE THREAD

**Issue by lc3t35** [unshiftio/url-parse#187] opened 2019-12-11 15:56 UTC
I'm using Expo Linking.parse which relies on url-parse, and my url includes an email with this allowed form "x+y@xxx.com".
Decoding is incorrect as show by this additional test in PR https://github.com/unshiftio/url-parse/pull/186

**Comment by lpinca** [comment] 2019-12-12 20:05
The third argument of the constructor accept a custom function which can be used to parse the query string. See https://github.com/unshiftio/url-parse#usage

By default https://github.com/unshiftio/querystringify is used which is limited by design.

**Comment by lc3t35** [comment] 2019-12-14 13:54
Thank you @lpinca , I've opened an issue for expo here https://github.com/expo/expo/issues/6528, so we can see how to fix this.
Can you dig a little why querystringify replaces a + (plus sign) by space in a param ?

**Comment by lpinca** [comment] 2019-12-14 14:06
See https://github.com/unshiftio/querystringify/issues/7

**Comment by lpinca** [comment] 2021-08-24 05:49
I'm closing this as answered.

**Closed by lpinca** 2021-08-24 05:49 UTC
